# Generated by Django 4.2.14 on 2024-09-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_intro_alter_customuser_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
