# Generated by Django 4.2.14 on 2024-09-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('男', 'Male'), ('女', 'Female')], max_length=1, null=True),
        ),
    ]
