# Generated by Django 4.2.14 on 2024-10-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_is_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('男', 'Male'), ('女', 'Female'), ('不透露', 'none')], max_length=3, null=True),
        ),
    ]
