# Generated by Django 4.2.14 on 2024-11-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skill_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
