# Generated by Django 4.2.14 on 2024-08-08 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        #('push_notifications', '0011_alter_apnsdevice_id_alter_gcmdevice_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0004_customapnsdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFCMDevice',
            fields=[
                ('gcmdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='push_notifications.gcmdevice')),
                ('custom_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('push_notifications.gcmdevice',),
        ),
        '''
        migrations.DeleteModel(
            name='CustomAPNSDevice',
        ),
        '''
    ]
