# Generated by Django 4.2.14 on 2024-09-19 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_delete_customuser'),
        ('notifications', '0008_notification_title_delete_schedulednotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('scheduled_time', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_notifications', to='events.event')),
            ],
            options={
                'ordering': ['scheduled_time'],
                'unique_together': {('event', 'scheduled_time')},
            },
        ),
    ]
