# Generated by Django 4.2.14 on 2024-09-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_schedulednotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulednotification',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='schedulednotification',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='schedulednotification',
            name='event',
        ),
        migrations.RemoveField(
            model_name='schedulednotification',
            name='scheduled_time',
        ),
    ]
