# Generated by Django 4.2.14 on 2024-09-19 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_alter_schedulednotification_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledNotification',
        ),
    ]
