# Generated by Django 4.2.14 on 2024-09-19 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_scheduledreminder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledReminder',
        ),
    ]
