# Generated by Django 4.2.14 on 2024-09-19 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_delete_scheduledreminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_celery_task',
        ),
    ]
