# Generated by Django 5.0.7 on 2024-07-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='number_of_people',
            field=models.IntegerField(default=0),
        ),
    ]
