# Generated by Django 5.0.7 on 2024-07-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_attendees_alter_event_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='spots_left',
            field=models.IntegerField(),
        ),
    ]
