# Generated by Django 5.0.7 on 2024-07-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
