# Generated by Django 5.0.7 on 2024-07-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='previously_approved',
            field=models.BooleanField(default=False),
        ),
    ]
