# Generated by Django 4.2.14 on 2024-08-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_net_type_alter_registration_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('open', '開放報名'), ('waitlist', '開放候補'), ('playing', '進行中'), ('past', '已結束')], default=('open', '開放報名'), max_length=20),
        ),
    ]
