# Generated by Django 4.2.14 on 2024-08-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('open', '開放報名'), ('waitlist', '開放候補'), ('past', '已結束')], default=('open', '開放報名'), max_length=20),
        ),
    ]
