# Generated by Django 4.2.14 on 2024-08-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancellation_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
