# Generated by Django 4.2.14 on 2024-09-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
