# Generated by Django 4.2.14 on 2024-10-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_registration_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_overnight',
            field=models.BooleanField(default=False),
        ),
    ]
