# Generated by Django 4.2.14 on 2024-11-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_event_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(choices=[('taipei', '台北市'), ('new_taipei', '新北市'), ('taoyuan', '桃園市'), ('taichung', '臺中市'), ('tainan', '臺南市'), ('kaohsiung', '高雄市'), ('keelung', '基隆市'), ('hsinchu_city', '新竹市'), ('hsinchu_county', '新竹縣'), ('miaoli', '苗栗縣'), ('changhua', '彰化縣'), ('nantou', '南投縣'), ('yunlin', '雲林縣'), ('chiayi_city', '嘉義市'), ('chiayi_county', '嘉義縣'), ('pingtung', '屏東縣'), ('yilan', '宜蘭縣'), ('hualien', '花蓮縣'), ('taitung', '臺東縣'), ('penghu', '澎湖縣'), ('kinmen', '金門縣'), ('lienchiang', '連江縣'), ('unspecified', '未填寫縣市')], default='unspecified', max_length=50),
        ),
    ]
