# Generated by Django 5.0.7 on 2024-07-24 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_registration_previously_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='net_type',
            field=models.CharField(choices=[('beach_volleyball', '沙灘排球'), ('women_net_mixed', '女網混排'), ('women_net_women', '女網女排'), ('men_net_men', '男網男排'), ('men_net_mixed', '男網混排'), ('mixed_net', '人妖網')], default=('beach_volleyball', '沙灘排球'), max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event'),
        ),
    ]
