# Generated by Django 4.2.14 on 2024-09-12 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
