# Generated by Django 5.0.7 on 2024-07-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='event',
        ),
        migrations.AddField(
            model_name='notification',
            name='event_id',
            field=models.IntegerField(null=True),
        ),
    ]
