# Generated by Django 4.2.14 on 2024-09-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_schedulednotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_celery_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
