# Generated by Django 4.2.14 on 2024-09-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_remove_notification_is_celery_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(null=True)),
                ('task_id', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
