# Generated by Django 4.2.14 on 2024-09-20 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_scheduledreminder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomFCMDevice',
        ),
    ]
